# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcname', models.CharField(max_length=100)),
                ('args', models.CharField(max_length=2000)),
                ('kwargs', models.CharField(max_length=2000)),
                ('jobtype', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asyncid', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
        migrations.CreateModel(
            name='TaskChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lasttask', models.CharField(max_length=50)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.Task')),
            ],
        ),
    ]
