# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='args',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='job',
            name='kwargs',
            field=models.CharField(max_length=10000),
        ),
    ]
