# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-11 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20191112_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobtype',
        ),
    ]
