# Generated by Django 3.1.2 on 2021-03-19 12:46

from django.db import migrations, models


def convert_nullstring_to_empty_list(apps, sce):
    Job = apps.get_model('jobs', 'Job')
    Task = apps.get_model('jobs', 'Task')
    Job.objects.filter(args='').update(args='[]')
    Task.objects.filter(args='').update(args='[]')


def revert_emptylist_to_nullstring(apps, sce):
    Job = apps.get_model('jobs', 'Job')
    Task = apps.get_model('jobs', 'Task')
    Job.objects.filter(args='[]').update(args='')
    Task.objects.filter(args='[]').update(args='')


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_job_jobtype'),
    ]

    operations = [
        migrations.RunPython(convert_nullstring_to_empty_list, revert_emptylist_to_nullstring),

        migrations.AlterField(
            model_name='job',
            name='args',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='funcname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='kwargs',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='args',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskchain',
            name='lasttask',
            field=models.TextField(),
        ),
    ]
