# Generated by Django 3.1.2 on 2021-03-22 19:12

from django.db import migrations, models


def put_args_in_kwargs(apps, sce):
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.exclude(args=[]):
        job.kwargs['args'] = job.args
        job.save()


def put_back_args(apps, sce):
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.filter(kwargs__args__isnull=False):
        job.args = job.kwargs.pop('args')
        job.save()
    Job.objects.filter(kwargs__args__isnull=True).update(args=[])



class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210319_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='args',
            field=models.JSONField(null=True),
        ),

        migrations.RunPython(put_args_in_kwargs, put_back_args),

        migrations.RemoveField(
            model_name='job',
            name='args',
        ),
    ]
