services:
    web:
        image: kantele_web
        depends_on:
            - db
        build:
            context: .
            dockerfile: ./docker/Dockerfile_web
            target: web_prod
        env_file:
            - ./docker/stage.env
        environment:
            KANTELEHOST: web
            DB_PASS: "${PG_KANTELE_PASSWORD}"
            DB_USER: kanteleuser
            DB_HOST: db
            DB_NAME: "${KANTELE_DB_NAME}"
            HOST_DOMAIN: "${HOST_FQDN}"
            RABBITHOST: mq
            RABBITUSER: "${RABBITUSER:-guest}"
            RABBITPASS: "${RABBITPASS:-guest}"
    
    nginx:
        image: kantele_nginx
        build:
            context: ./
            dockerfile: ./docker/Dockerfile_web
            target: nginx
        depends_on:
            - web
        ports:
            - 80:80
    db:
        image: postgres:14.3
        ## Comment user: line on MacOS, not on linux
        user: "${DBUID:-0}:${DBGID:-0}"
        environment:
            POSTGRES_PASSWORD: "${PG_SUPERUSER_PASSWORD}"
            KANTELE_PASSWORD: "${PG_KANTELE_PASSWORD}"
            KANTELE_DB: "${KANTELE_DB_NAME}"
            KANTELE_ROLE: kanteleuser

    mq:
        image: rabbitmq:3.10
        environment:
            RABBITMQ_DEFAULT_USER: "${RABBITUSER:-guest}"
            RABBITMQ_DEFAULT_PASS: "${RABBITPASS:-guest}"

    jobrunner:
        image: kantele_web
        depends_on:
            - web
        command: python manage.py runjobs
        env_file:
            - ./docker/stage.env
        environment:
            DB_PASS: "${PG_KANTELE_PASSWORD}"
            DB_USER: kanteleuser
            DB_HOST: db
            DB_NAME: "${KANTELE_DB_NAME}"
            HOST_DOMAIN: "${HOST_FQDN}"
            RABBITHOST: mq
            RABBITUSER: "${RABBITUSER:-guest}"
            RABBITPASS: "${RABBITPASS:-guest}"
