services:
    web:
        extends:
            file: docker-compose-prod.yml
            service: web
        env_file:
            - ./src/docker/stage.env
        volumes:
          - ./src/backend:/kantele
        environment:
            PROTOCOL: http
    
    nginx:
        image: kantele_nginx_stage
        build:
            context: ./src
            dockerfile: ./docker/Dockerfile
            target: nginx_stage
        depends_on:
            - web
        ports:
            - 80:80
        volumes:
            - ./src/docker/uwsgi_params:/etc/nginx/uwsgi_params
            - ./src/docker/nginx_stage.conf:/etc/nginx/nginx.conf
            - ./src/static:/static

    db: 
        extends:
            file: docker-compose-prod.yml
            service: db 
        volumes:
            - "./src/docker/create_kantele_db.sh:/kantele_db_init/create_kantele_db.sh"

    mq:
        extends:
            file: docker-compose-prod.yml
            service: mq

    jobrunner:
        extends:
            file: docker-compose-prod.yml
            service: jobrunner
        env_file:
            - ./src/docker/stage.env
        volumes:
            - ./src/backend:/kantele
