services:
    web:
        extends:
            file: docker-compose-prod.yml
            service: web
        volumes:
          - ./backend:/kantele
    
    nginx:
        extends:
            file: docker-compose-prod.yml
            service: nginx 
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/uwsgi_params:/etc/nginx/uwsgi_params
            - ./static:/static

    db: 
        extends:
            file: docker-compose-prod.yml
            service: db 
        volumes:
            - "${PG_DATA_PATH}:/var/lib/postgresql/data"
            - "./docker/create_kantele_db.sh:/kantele_db_init/create_kantele_db.sh"
            - "${BACKUP_PATH}:/backups"

    mq:
        extends:
            file: docker-compose-prod.yml
            service: mq
        volumes:
            - "./docker/rabbitmq-timeout.conf:/etc/rabbitmq/conf.d/30-timeout.conf"

    jobrunner:
        extends:
            file: docker-compose-prod.yml
            service: jobrunner
        volumes:
            - ./backend:/kantele
