services:
    web:
        extends:
            file: docker-compose-prod.yml
            service: web
        env_file:
            - prod-container.env
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
    
    nginx:
        extends:
            file: docker-compose-prod.yml
            service: nginx
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        volumes:
            - "{{ tls_path }}:/{{ tls_path }}"

    db: 
        extends:
            file: docker-compose-prod.yml
            service: db
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"

    mq:
        extends:
            file: docker-compose-prod.yml
            service: mq
        ports:
            - 5672:5672
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"


    jobrunner:
        extends:
           file: docker-compose-prod.yml
           service: jobrunner
        env_file:
            - prod-container.env
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
