services:
    web:
        extends:
            file: docker-compose-prod.yml
            service: web
        env_file:
            - ./src/docker/stage.env
        volumes:
          - ./src/backend:/kantele
    
    nginx:
        extends:
            file: docker-compose-prod.yml
            service: nginx 
        volumes:
            - ./src/docker/nginx_stage.conf:/etc/nginx/nginx.conf
            - ./src/docker/uwsgi_params:/etc/nginx/uwsgi_params
            - ./src/static:/static

    db: 
        extends:
            file: docker-compose-prod.yml
            service: db 
        volumes:
            - "${PG_DATA_PATH}:/var/lib/postgresql/data"
            - "./src/docker/create_kantele_db.sh:/kantele_db_init/create_kantele_db.sh"

    mq:
        extends:
            file: docker-compose-prod.yml
            service: mq
        volumes:
            - "./src/docker/rabbitmq-timeout.conf:/etc/rabbitmq/conf.d/30-timeout.conf"

    jobrunner:
        extends:
            file: docker-compose-prod.yml
            service: jobrunner
        env_file:
            - ./src/docker/stage.env
        volumes:
            - ./src/backend:/kantele
