# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20180717_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='log',
            field=models.TextField(default=''),
        ),
    ]
