# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_paramoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemblfasta',
            name='organism',
            field=models.TextField(default='Homo sapiens'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniprotfasta',
            name='isoforms',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniprotfasta',
            name='organism',
            field=models.TextField(default='Homo sapiens'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ensemblfasta',
            name='libfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.LibraryFile'),
        ),
    ]
