# Generated by Django 3.2.7 on 2021-09-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_auto_20210820_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileparam',
            name='help',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='param',
            name='help',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
