services:
    web:
        network_mode: host
        depends_on:
            - db
            - mq
        env_file:
            - ./prod-container.env
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        environment:
            PROTOCOL: https
            DB_HOST: "${HOST_FQDN}"
            RABBITHOST: "${HOST_FQDN}"
        volumes:
            - "${HOST_UPLOADPATH}:${CONTAINER_UPLOADPATH}"
            - "${HOST_ANALYSISFILES}:${CONTAINER_ANALYSISPATH}"
    
    nginx:
        network_mode: host
        depends_on:
            - web
        image: kantele_nginx
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
            target: nginx_prod
            args:
                USER_ID: "${USER_ID:-You must run export USER_ID}"
                GROUP_ID: "${GROUP_ID:-You must run export GROUP_ID}"
        volumes:
            - "${HOST_UPLOADPATH}:${CONTAINER_UPLOADPATH}"
            - "${HOST_ANALYSISFILES}:${CONTAINER_ANALYSISPATH}"
            - "${HOST_TLSCERTPATH}:/${CONTAINER_TLSCERTPATH}"
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"

    db: 
        network_mode: host
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        volumes:
            - "${PG_DATA_PATH}:/var/lib/postgresql/data"
            - "${HOST_PG_BACKUPS}:/pgbackups"


    mq:
        network_mode: host
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        volumes:
            - "./rabbitmq-timeout.conf:/etc/rabbitmq/conf.d/30-timeout.conf"


    jobrunner:
        depends_on:
            - web
            - mq
        network_mode: host
        env_file:
            - ./prod-container.env
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        environment:
            DB_HOST: "${HOST_FQDN}"
            RABBITHOST: "${HOST_FQDN}"
