# Base compose recipe, dev, prod and others can use this

services:
    web:
        image: kantele_web
        depends_on:
            - db
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
            target: django
            args:
                USER_ID: "${USER_ID:-You must run export USER_ID}"
                GROUP_ID: "${GROUP_ID:-You must run export GROUP_ID}"
        environment:
            KANTELEHOST: "${HOST_FQDN}"
            DB_PASS: "${PG_KANTELE_PASSWORD}"
            DB_USER: "${PG_KANTELE_USER}"
            DB_NAME: "${KANTELE_DB_NAME}"
            HOST_DOMAIN: "${HOST_FQDN}"
            RABBIT_VHOST: "${RABBIT_VHOST}"
            RABBITUSER: "${RABBITUSER:-guest}"
            RABBITPASS: "${RABBITPASS:-guest}"
            TMP_UPLOADPATH: "${CONTAINER_UPLOADPATH}"
            SERVABLE_FILE_PATH: "${CONTAINER_ANALYSISPATH}"
        volumes:
            - "${HOST_UPLOADPATH}:${CONTAINER_UPLOADPATH}"
            - "${HOST_ANALYSISFILES}:${CONTAINER_ANALYSISPATH}"
    
    nginx:
        image: kantele_nginx
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
            target: nginx_prod
            args:
                USER_ID: "${USER_ID:-You must run export USER_ID}"
                GROUP_ID: "${GROUP_ID:-You must run export GROUP_ID}"
        depends_on:
            - web
        volumes:
            - "${HOST_UPLOADPATH}:${CONTAINER_UPLOADPATH}"
            - "${HOST_ANALYSISFILES}:${CONTAINER_ANALYSISPATH}"

    db:
        image: postgres:14.3
        ## Comment user: line on MacOS, not on linux
        user: "${DBUID:-0}:${DBGID:-0}"
        environment:
            POSTGRES_PASSWORD: "${PG_SUPERUSER_PASSWORD}"
        volumes:
            - "${PG_DATA_PATH}:/var/lib/postgresql/data"

    mq:
        image: rabbitmq:3.10
        environment:
            RABBITMQ_DEFAULT_USER: "${RABBITUSER:-guest}"
            RABBITMQ_DEFAULT_PASS: "${RABBITPASS:-guest}"
            RABBITMQ_DEFAULT_VHOST: "${RABBIT_VHOST}"
            #volumes:
            #- "./src/docker/rabbitmq-timeout.conf:/etc/rabbitmq/conf.d/30-timeout.conf"

    jobrunner:
        image: kantele_web
        depends_on:
            - web
        command: python manage.py runjobs
        environment:
            DB_PASS: "${PG_KANTELE_PASSWORD}"
            DB_USER: kanteleuser
            DB_NAME: "${KANTELE_DB_NAME}"
            HOST_DOMAIN: "${HOST_FQDN}"
            RABBIT_VHOST: "${RABBIT_VHOST}"
            RABBITUSER: "${RABBITUSER:-guest}"
            RABBITPASS: "${RABBITPASS:-guest}"
