services:
    web:
        env_file:
            - ./prod-container.env
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
    
    nginx:
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        volumes:
            - "${HOST_TLSCERTPATH}:/${CONTAINER_TLSCERTPATH}"

    db: 
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        volumes:
            - "${PG_DATA_PATH}:/var/lib/postgresql/data"
            - "${HOST_PG_BACKUPS}:/pgbackups"


    mq:
        ports:
            - 5672:5672
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        volumes:
            - "./src/docker/rabbitmq-timeout.conf:/etc/rabbitmq/conf.d/30-timeout.conf"


    jobrunner:
        env_file:
            - ./prod-container.env
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
