services:
    web:
        network_mode: host
        depends_on:
            - db
            - mq
        env_file:
            - ./prod-container.env
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        environment:
            PROTOCOL: https
            DB_HOST: "${HOST_FQDN}"
            RABBITHOST: "${HOST_FQDN}"
    
    nginx:
        network_mode: host
        depends_on:
            - web
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        volumes:
            - "${HOST_TLSCERTPATH}:/${CONTAINER_TLSCERTPATH}"

    db: 
        network_mode: host
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        volumes:
            - "${PG_DATA_PATH}:/var/lib/postgresql/data"
            - "${HOST_PG_BACKUPS}:/pgbackups"


    mq:
        network_mode: host
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        volumes:
            - "./rabbitmq-timeout.conf:/etc/rabbitmq/conf.d/30-timeout.conf"


    jobrunner:
        depends_on:
            - web
            - mq
        network_mode: host
        env_file:
            - ./prod-container.env
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_ADDRESS}"
        environment:
            DB_HOST: "${HOST_FQDN}"
            RABBITHOST: "${HOST_FQDN}"
