services:
    web:
        image: kantele_web
        build:
            context: ./src
            dockerfile: ./docker/Dockerfile
            target: django
            args:
                USER_ID: "${USER_ID:-You must run export USER_ID}"
                GROUP_ID: "${GROUP_ID:-You must run export GROUP_ID}"
    
    nginx:
        image: kantele_nginx
        build:
            context: ./src
            dockerfile: ./docker/Dockerfile
            target: nginx_prod
            args:
                USER_ID: "${USER_ID:-You must run export USER_ID}"
                GROUP_ID: "${GROUP_ID:-You must run export GROUP_ID}"
