services:
    web:
        image: django_test
        build:
            context: ./src
            dockerfile: ./docker/Dockerfile
            target: django_test
            args:
                USER_ID: "${USER_ID:-You must run export USER_ID}"
                GROUP_ID: "${GROUP_ID:-You must run export GROUP_ID}"
    
    upload_bay_rsync:
        image: rsync_stor
        build:
            context: ./src
            dockerfile: ./docker/Dockerfile
            target: rsync_storage
            args:
                USER_ID: "${USER_ID:-You must run export USER_ID}"
                GROUP_ID: "${GROUP_ID:-You must run export GROUP_ID}"
