# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_analysis_purged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryfile',
            name='sfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.StoredFile'),
        ),
    ]
