# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_workflowfileparam_allow_resultfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsemblFasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(unique=True)),
                ('libfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.LibraryFile')),
            ],
        ),
        migrations.CreateModel(
            name='UniProtFasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField(unique=True)),
                ('libfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.LibraryFile')),
            ],
        ),
    ]
