# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-15 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_auto_20200826_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsetComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WFInputComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='psetcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.WFInputComponent'),
        ),
        migrations.AddField(
            model_name='psetcomponent',
            name='pset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.ParameterSet'),
        ),
    ]
