# Generated by Django 3.1.2 on 2021-04-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_analysisname_without_wftype'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextflowsearch',
            name='token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
