# Generated by Django 3.2.13 on 2022-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_proteowizard_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextflowwfversion',
            name='profiles',
            field=models.JSONField(default=list),
        ),
    ]
