# Generated by Django 3.2.13 on 2022-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0039_auto_20221207_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniprotfasta',
            name='dbtype',
            field=models.IntegerField(choices=[(0, 'Swiss_canonical'), (1, 'Swiss_canonical_isoforms'), (2, 'Reference_proteome'), (3, 'Reference_proteome_isoforms')]),
        ),
    ]
