# Generated by Django 3.2.13 on 2023-01-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0041_analysis_output_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfoutput',
            name='psmscorefield',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
