# Generated by Django 3.2.13 on 2023-11-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0042_auto_20230914_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psetcomponent',
            name='component',
            field=models.IntegerField(choices=[(1, 'Isobaric quant summarizing with denominators, median sweep, or intensity'), (2, 'Input file definition of specific type, value eg [path, instrument, sample]'), (3, 'Sampletable for isobaric quant'), (4, 'MS search complementing earlier run or rerun from PSMs'), (5, 'MS search complementing earlier run or rerun from PSMs'), (6, 'Prefractionated MS data'), (7, 'HiRIEF strip tolerance')]),
        ),
        migrations.AlterField(
            model_name='psetcomponent',
            name='value',
            field=models.JSONField(default=dict),
        ),
        migrations.RenameModel(
            old_name='DatasetSearch',
            new_name='DatasetAnalysis',
        ),
    ]
