# Generated by Django 3.2.13 on 2024-02-19 13:55

from django.db import migrations, models


def populate_nfwf_m2m(apps, s):
    WF = apps.get_model('analysis', 'Workflow')
    for wf in WF.objects.all():
        for nfwfv in wf.nfworkflow.nextflowwfversion_set.all():
            wf.nfworkflows.add(nfwfv)


def reverse_m2m(apps, s):
    WF = apps.get_model('analysis', 'Workflow')
    for wf in WF.objects.all():
        wf.nfworkflow = wf.nfworkflows.last().nfworkflow


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0044_deletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='nfworkflows',
            field=models.ManyToManyField(to='analysis.NextflowWfVersion'),
        ),

        migrations.RunPython(populate_nfwf_m2m, reverse_m2m),

        migrations.RemoveField(
            model_name='workflow',
            name='nfworkflow',
        ),
        migrations.AlterField(
            model_name='psetcomponent',
            name='component',
            field=models.IntegerField(choices=[(1, 'Isobaric quant summarizing with denominators, median sweep, or intensity'), (2, 'Input file definition of specific type, value eg [path, instrument, sample]'), (3, 'Sampletable for isobaric quant'), (4, 'Labelcheck isoquant'), (5, 'MS search complementing earlier run or rerun from PSMs'), (6, 'Prefractionated MS data'), (7, 'HiRIEF strip tolerance')]),
        ),
    ]
