# Generated by Django 3.2.13 on 2024-03-25 14:32

from django.db import migrations, models


def populate_ptype_to_choice(apps, s):
    P = apps.get_model('analysis', 'Param')
    P.objects.filter(ptype='flag').update(ptype=1)
    P.objects.filter(ptype='multi').update(ptype=2)
    P.objects.filter(ptype='text').update(ptype=3)
    P.objects.filter(ptype='number').update(ptype=4)


def reverse_ptype_to_choice(apps, s):
    P = apps.get_model('analysis', 'Param')
    P.objects.filter(ptype=1).update(ptype='flag')
    P.objects.filter(ptype=2).update(ptype='multi')
    P.objects.filter(ptype=3).update(ptype='text')
    P.objects.filter(ptype=4).update(ptype='number')


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0046_auto_20240223_1357'),
    ]

    operations = [
        migrations.RunPython(populate_ptype_to_choice, reverse_ptype_to_choice),

        migrations.AlterField(
            model_name='param',
            name='ptype',
            field=models.IntegerField(choices=[(1, 'Flag'), (2, 'Multiple choice checkbox'), (3, 'Text'), (4, 'Numbers, integers, floats'), (5, 'Single choice select')]),
        ),
    ]
