# Generated by Django 3.2.13 on 2024-03-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0028_alter_storedfile_checked'),
        ('datasets', '0019_deletes'),
        ('analysis', '0047_alter_param_ptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFileValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('sfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.storedfile')),
            ],
        ),
        migrations.RenameModel(
            old_name='AnalysisDatasetSetname',
            new_name='AnalysisDatasetSetValue',
        ),
        migrations.DeleteModel(
            name='AnalysisFileSample',
        ),
        migrations.AddConstraint(
            model_name='analysisfilevalue',
            constraint=models.UniqueConstraint(fields=('analysis', 'sfile'), name='uni_anassamplefile'),
        ),
        migrations.RemoveConstraint(
            model_name='analysisdsinputfile',
            name='uni_anainfile',
        ),
        migrations.AddField(
            model_name='analysisdsinputfile',
            name='analysisset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analysis.analysissetname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisdsinputfile',
            name='dsanalysis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analysis.datasetanalysis'),
            preserve_default=False,
        ),
    ]
