# Generated by Django 3.2.13 on 2024-03-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0028_alter_storedfile_checked'),
        ('datasets', '0019_deletes'),
        ('analysis', '0047_alter_param_ptype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalysisDatasetSetname',
            new_name='AnalysisDatasetSetValue',
        ),
        migrations.RenameModel(
            old_name='AnalysisFileSample',
            new_name='AnalysisFileValue',
        ),
        migrations.RenameField(
            model_name='AnalysisFileValue',
            old_name='sample',
            new_name='value',
        ),
        migrations.RemoveConstraint(
            model_name='analysisdsinputfile',
            name='uni_anainfile',
        ),
        migrations.RemoveConstraint(
            model_name='analysisfilevalue',
            name='uni_anassamplefile',
        ),
        migrations.AddField(
            model_name='analysisdsinputfile',
            name='analysisset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analysis.analysissetname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisdsinputfile',
            name='dsanalysis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analysis.datasetanalysis'),
            preserve_default=False,
        ),
    ]
