# Generated by Django 3.2.13 on 2024-03-27 11:44

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import OuterRef, Subquery


def remove_dups(apps, s):
    DSA = apps.get_model('analysis', 'DatasetAnalysis')
    for dsa in DSA.objects.all()[::-1]:
        if DSA.objects.filter(dataset=dsa.dataset, analysis=dsa.analysis).count() > 1:
            dsa.delete()


def populate_analysisset(apps, s):
    ADSI = apps.get_model('analysis', 'AnalysisDSInputFile')
    ADSI.objects.update(analysisset=Subquery(ADSI.objects.filter(pk=OuterRef('pk')).values('analysisdset__setname')[:1]))


def moveback_analysisset(apps, s):
    pass


def populate_dsanalysis(apps, s):
    ADSI = apps.get_model('analysis', 'AnalysisDSInputFile')
    ADSV = apps.get_model('analysis', 'AnalysisDatasetSetValue')
    DSA = apps.get_model('analysis', 'DatasetAnalysis')
    ADSI.objects.update(dsanalysis=Subquery(DSA.objects.filter(
        dataset=Subquery(ADSV.objects.filter(pk=OuterRef(OuterRef('analysisdset'))).values('dataset')[:1]),
        analysis=OuterRef('analysis')).values('pk')[:1]))


def moveback_dsanalysis(apps, s):
    pass

def fake(apps, s):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0048_auto_20240326_1509'),
    ]

    operations = [
        migrations.RunPython(remove_dups, fake),
        migrations.RunPython(populate_analysisset, moveback_analysisset),
        migrations.RunPython(populate_dsanalysis, moveback_dsanalysis),
    ]
