# Generated by Django 3.2.13 on 2024-03-27 20:33

from django.db import migrations, models


def sample_or_regex_to_field(apps, s):
    ADSV = apps.get_model('analysis', 'AnalysisDatasetSetValue')
    ADSV.objects.filter(regex='').delete()
    ADSV.objects.update(field='__regex', value=models.F('regex'))
    AFS = apps.get_model('analysis', 'AnalysisFileValue')
    AFS.objects.update(field='__sample')


def fake(a, s):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0050_delete_old_fields_20240327_1350'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysisdatasetsetvalue',
            name='uni_anadsets',
        ),
        migrations.AddField(
            model_name='analysisdatasetsetvalue',
            name='field',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisdatasetsetvalue',
            name='value',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisfilevalue',
            name='field',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RunPython(sample_or_regex_to_field, fake),

        migrations.AddConstraint(
            model_name='analysisdatasetsetvalue',
            constraint=models.UniqueConstraint(fields=('analysis', 'dataset', 'field'), name='uni_anadsetsfields'),
        ),
        migrations.AddConstraint(
            model_name='analysisfilevalue',
            constraint=models.UniqueConstraint(fields=('analysis', 'sfile', 'field'), name='uni_anassamplefile'),
        ),
        migrations.RemoveField(
            model_name='analysisdatasetsetvalue',
            name='regex',
        ),
    ]
