# Generated by Django 4.2 on 2024-10-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0051_auto_20240327_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputFieldName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Short description')),
                ('fieldname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WfOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('psmfile', models.TextField()),
                ('pepfile', models.TextField()),
                ('genefile', models.TextField()),
                ('fasta_arg', models.TextField()),
                ('genetablegenefield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genegene', to='analysis.outputfieldname')),
                ('pepfdrfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepfdr', to='analysis.outputfieldname')),
                ('pepms1field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepms1', to='analysis.outputfieldname')),
                ('peppepfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepposterior', to='analysis.outputfieldname')),
                ('peppeptidefield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peppep', to='analysis.outputfieldname')),
                ('psmchargefield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge', to='analysis.outputfieldname')),
                ('psmfdrfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psmfdr', to='analysis.outputfieldname')),
                ('psmfnfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fn', to='analysis.outputfieldname')),
                ('psmms1field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psmms1', to='analysis.outputfieldname')),
                ('psmmzfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psmmz', to='analysis.outputfieldname')),
                ('psmpepfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psmposterior', to='analysis.outputfieldname')),
                ('psmpeptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psmpep', to='analysis.outputfieldname')),
                ('psmprotfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prot', to='analysis.outputfieldname')),
                ('psmscorefield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='analysis.outputfieldname')),
                ('psmsetname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psmset', to='analysis.outputfieldname')),
                ('rtfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psmrt', to='analysis.outputfieldname')),
                ('scanfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psmscan', to='analysis.outputfieldname')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineVersionOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfwfversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.nextflowwfversionparamset')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.wfoutput')),
            ],
        ),
    ]
