# Generated by Django 4.2 on 2024-10-15 08:51

from django.db import migrations, models
import django.db.models.deletion

from jobs import jobs as jj


def determine_editable(a, s):
    Ana = a.get_model('analysis', 'Analysis')
    Ana.objects.exclude(nextflowsearch__job__state__in=jj.JOBSTATES_PRE_OK_JOB).update(editable=False)


def fake(a, s):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0031_remove_uploadtoken_is_library_uploadtoken_uploadtype'),
        ('analysis', '0052_outputfieldname_wfoutput_pipelineversionoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='editable',
            field=models.BooleanField(default=True),
        ),

        migrations.RunPython(determine_editable, fake),

        migrations.AlterField(
            model_name='userworkflow',
            name='wftype',
            field=models.IntegerField(choices=[(1, 'Quantitative proteomics'), (2, 'Instrument quality control'), (3, 'Other proteomics, special DB'), (4, 'Proteogenomics DB generation'), (5, 'pI-separated identification'), (6, 'Special internal'), (7, 'Labelcheck'), (8, 'User-run workflow')]),
        ),
        migrations.CreateModel(
            name='ExternalAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('last_token', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rawstatus.uploadtoken')),
            ],
        ),
    ]
