# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0004_auto_20180912_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='filetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.StoredFileType'),
        ),
    ]
