# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-15 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0006_auto_20180930_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 11, 31, 20, 773071, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
