# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0010_auto_20181015_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='purged',
            field=models.BooleanField(default=False),
        ),
    ]
