# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0011_storedfile_purged'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDCBackedupFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdcpath', models.TextField()),
                ('success', models.BooleanField()),
                ('deleted', models.BooleanField(default=False)),
                ('storedfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.StoredFile')),
            ],
        ),
    ]
