# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0012_pdcbackedupfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
