# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-02 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def initialize_instruments(apps, schema_editor):
    MSInsType = apps.get_model('rawstatus', 'MSInstrumentType')
    MSInsType.objects.bulk_create([MSInsType(name=x) for x in ['timstof', 'qe', 'velos']])


def fakerevert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0014_auto_20191206_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSInstrumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),

        migrations.RunPython(initialize_instruments, fakerevert),

        migrations.RenameModel(old_name='ProducerFileType', new_name='MSInstrument'),

        migrations.AddField(
            model_name='msinstrument',
            name='instrumenttype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rawstatus.MSInstrumentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedfiletype',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
    ]
