# Generated by Django 3.2.7 on 2021-09-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0021_auto_20210331_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='md5',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
