# Generated by Django 3.1.2 on 2021-09-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0021_auto_20210331_1956'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storedfile',
            constraint=models.UniqueConstraint(fields=('rawfile', 'filetype', 'servershare', 'path'), name='uni_storedfile'),
        ),
    ]
