# Generated by Django 3.2.7 on 2021-12-14 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('rawstatus', '0023_auto_20211213_1332'), ('rawstatus', '0024_rename_userfileupload_uploadtoken'), ('rawstatus', '0025_auto_20211213_1534')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawstatus', '0022_md5_storedfile_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfileupload',
            name='finished',
        ),
        migrations.AddField(
            model_name='producer',
            name='internal',
            field=models.BooleanField(default=False, help_text='Internal instrument with own raw file upload client'),
        ),
        migrations.RenameModel(
            old_name='UserFileUpload',
            new_name='UploadToken',
        ),
        migrations.AddField(
            model_name='uploadtoken',
            name='expired',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadtoken',
            name='producer',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='rawstatus.producer'),
            preserve_default=False,
        ),
    ]
