FROM python:3.10.4

RUN apt-get update && apt-get install -y libpq-dev python3-psycopg2 nodejs nginx

COPY docker/requirements.txt /
RUN pip install -r requirements.txt

COPY backend /kantele

# FIXME add node compile of frontend

WORKDIR /kantele
CMD uwsgi --socket :8009 --processes 3 --module kantele.wsgi
