FROM python:3.10.4

RUN apt-get update && apt-get install -y libpq-dev python3-psycopg2 nodejs nginx

COPY docker/requirements.txt /
RUN pip install -r requirements.txt

COPY backend /kantele

# FIXME add node compile of frontend

CMD cd /kantele && python manage.py runserver -v 3 0.0.0.0:80
# FIXME add nginx to here
