# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '__first__'),
        ('rawstatus', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxplotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=15)),
                ('upper', models.FloatField()),
                ('lower', models.FloatField()),
                ('q1', models.FloatField()),
                ('q2', models.FloatField()),
                ('q3', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LineplotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('shortname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QCData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis')),
                ('rawfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.RawFile')),
            ],
        ),
        migrations.AddField(
            model_name='lineplotdata',
            name='qcrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.QCData'),
        ),
        migrations.AddField(
            model_name='boxplotdata',
            name='qcrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.QCData'),
        ),
    ]
