---
- hosts: analysis
  remote_user: "{{ analysis_connect_user }}"
  tasks:
    - name: Stop running workers
      ansible.builtin.import_tasks:
        file: stop_celery.yml

    - name: Specific analysis tasks
      ansible.builtin.import_tasks:
        file: analysis_tasks.yml
      when: onlystop is undefined

    - name: General kantele/celery updates
      ansible.builtin.import_tasks:
        file: update_analysis_storage_tasks.yml
      when: onlystop is undefined
