# Playbook to stop analysis workers
#
- hosts: analysis
  remote_user: '{{ analysis_connect_user }}'
  tasks:
      - name: Stop celery
        become: yes
        systemd:
            state: stopped 
            daemon_reload: yes
            name: kantele_analysis
