---
# Playbook for updating analysis

- hosts: analysis
  remote_user: jorrit
  tasks:
      - name: Update kantele code
        become: yes
        become_user: "{{ kanteleuser }}"
        git:
            repo: '{{ kantele_repo }}'
            dest: "{{ kanteledir }}"
            version: master
  
      - name: Update virtualenv
        become: yes
        become_user: "{{ kanteleuser }}"
        pip:
            requirements: "{{ kanteledir }}/src/backend/requirements.txt"
            virtualenv_python: "/usr/bin/python3"
            virtualenv: "{{ kantelevenv }}"

      - name: Kantele celery env file
        become: yes
        become_user: "{{ kanteleuser }}"
        template:
            src: celery_analysis_systemd_env.j2
            dest: "{{ celeryenv_file }}"
            mode: 0400

      - name: Kantele celery analysis tasks
        become: yes
        template:
            src: analysis_celery_systemd.j2
            dest: /etc/systemd/system/kantele_analysis.service
            mode: 0644
