---
# Playbook for starting services on storage servers

- hosts: storage
  remote_user: '{{ storage_connect_user }}'
  become: yes
  become_user: '{{ storage_user }}'
  tasks:
      - name: Update kantele code
        git:
            repo: "{{ kantele_repo }}"
            dest: "{{ kanteledir }}"
            version: master
  
            #- name: FIXME passwordless SSH key to use for rsync from web server
      - name: Backup download -- create folder for backups
        ansible.builtin.file:
            path: "{{ storage_backup_path }}"
            state: directory

      - name: Backup download -- template out backup script
        ansible.builtin.template:
            src: "download_backup.j2"
            dest: "{{ kanteledir }}/download_backup.sh"

      - name: Backup download -- crontab setup 
        # FIXME how to error report?
        ansible.builtin.cron:
            name: Download kantele DB dump backup
            hour: "3"
            minute: "*/5"
            job: "bash {{ kanteledir }}/download_backup.sh"

      - name: Update virtualenv on storage (SCL, so use shell script)
        shell:
            cmd: "scl enable rh-python36 rh-postgresql12 -- {{ kantelevenv }}/bin/pip install -r {{ kanteledir }}/src/backend/requirements.txt"
      - name: Transfer start script
        template:
            src: "{{ item }}.j2"
            dest: "{{ kanteledir }}/{{ item }}.sh"
        loop:
            - "storage_dl"
            - "storage_pdc"
            - "storage_local"
