---
# Playbook for starting local moving services on storage servers (kalevala, totoro)

- hosts: storage
  remote_user: '{{ storage_user }}'
  tasks:
      - name: Transfer start script
        template:
            src: storage_local.j2
            dest: "{{ kanteledir }}/storage_local.sh"

      - name: Start celery download queue worker
        command: "scl enable rh-python36 rh-postgresql12 -- bash {{ kanteledir }}/storage_local.sh"
        args:
            chdir: "{{ kanteledir }}"
        environment: "{{ storage_env }}"
