---
# Playbook for starting services on storage servers

- hosts: storage
  remote_user: '{{ storage_connect_user }}'
  become: yes
  become_user: '{{ storage_user }}'
  tasks:
      - name: Start file management (storage, MD5)
        command: "scl enable rh-python36 rh-postgresql12 -- bash {{ kanteledir }}/{{ item }}.sh"
        args:
            chdir: "{{ kanteledir }}/src/backend"
        environment: "{{ storage_env }}"
        loop:
            - "storage_dl"
            - "storage_pdc"
            - "storage_local"
