---
# Playbook for starting services on storage servers (kalevala, totoro)

- hosts: storage
  become: yes
  become_user: '{{ storage_user }}'
  tasks:
      - name: Update kantele code
        become: yes
        become_user: "{{ kanteleuser }}"
        git:
            repo: 'https://github.com/glormph/kantele'
            dest: "{{ kanteledir }}"
            version: master
  
      - name: Update virtualenv on storage (SCL, so use shell script)
        become: yes
        become_user: "{{ kanteleuser }}"
        shell:
            cmd: "scl enable rh-python36 rh-postgresql12 -- {{ kantelevenv }}/bin/pip install -r {{ kanteledir }}/requirements.txt"

      - name: Get celery processes running
        shell: "ps x | grep -v grep | grep -w celery | awk '{print $1}'"
        register: running_celery

      - name: Kill running celery
        command: "kill {{ item }}"
        register: result
        failed_when:
            - result.rc != 0
            - "'no process killed' not in result.stderr"
            - "'No such process' not in result.stderr"
        loop: "{{ running_celery.stdout_lines }}"

      - wait_for:
          path: "/proc/{{ item }}/status"
          state: absent
          timeout: 300
        loop: "{{ running_celery.stdout_lines }}"
        ignore_errors: yes
        register: killed_processes
         
      - name: Kill -9 celery that doesnt die
        shell: "kill -9 {{ item }}"
        loop: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"

      - name: Transfer start script
        template:
            src: "{{ item }}.j2"
            dest: "{{ kanteledir }}/{{ item }}.sh"
        loop:
            - "storage_dl"
            - "storage_pdc"
            - "storage_local"

      - name: Start file management (storage, MD5)
        command: "scl enable rh-python36 rh-postgresql12 -- bash {{ kanteledir }}/{{ item }}.sh"
        args:
            chdir: "{{ kanteledir }}"
        environment: "{{ storage_env }}"
        loop:
            - "storage_dl"
            - "storage_pdc"
            - "storage_local"
