---
- hosts: storage
  remote_user: "{{ storage_connect_user }}"
  tasks:
    - name: Stop running workers
      ansible.builtin.import_tasks:
        file: stop_celery.yml

    - name: Specific storage tasks
      ansible.builtin.import_tasks:
        file: storage_tasks.yml

    - name: General kantele/celery updates
      ansible.builtin.import_tasks:
        file: update_analysis_storage_tasks.yml
