# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corefac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corefacuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='CorefacUser',
        ),
    ]
