# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 08:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
        ('datasets', '0001_initial'),
        ('rawstatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis')),
                ('sfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.StoredFile')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('sfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.StoredFile')),
            ],
        ),
        migrations.CreateModel(
            name='NextflowSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
        migrations.CreateModel(
            name='NextflowWfVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(help_text='Description of workflow update', max_length=200)),
                ('commit', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NextflowWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of workflow', max_length=200)),
                ('repo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='nextflowwfversion',
            name='nfworkflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.NextflowWorkflow'),
        ),
        migrations.AddField(
            model_name='nextflowsearch',
            name='nfworkflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.NextflowWfVersion'),
        ),
    ]
