# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nfparam', models.CharField(max_length=50)),
                ('filetype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nfparam', models.CharField(max_length=50)),
                ('ptype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nfworkflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.NextflowWorkflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowFileParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FileParam')),
                ('wf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Param')),
                ('wf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowPredefFileParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.LibraryFile')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FileParam')),
                ('wf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='workflow',
            name='shortname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.WorkflowType'),
        ),
    ]
