# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20180516_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextflowsearch',
            name='workflow',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='analysis.Workflow'),
            preserve_default=False,
        ),
    ]
