# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-02 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysis_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
