# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-30 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20180930_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
