# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_analysis_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='purged',
            field=models.BooleanField(default=False),
        ),
    ]
