# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-04 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0016_auto_20200404_1827'),
        ('analysis', '0015_ensemblfasta_uniprotfasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MzmlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proteowizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_description', models.TextField()),
                ('container_version', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_docker', models.BooleanField(default=False)),
                ('nf_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.NextflowWfVersion')),
            ],
        ),
        migrations.AddField(
            model_name='mzmlfile',
            name='pwiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Proteowizard'),
        ),
        migrations.AddField(
            model_name='mzmlfile',
            name='sfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.StoredFile'),
        ),
    ]
