# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-17 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_one_pset(apps, sch_ed):
    PS = apps.get_model('analysis', 'ParameterSet')
    PS.objects.create(name='fake test paramset')

def fakerevert(apps, sch_ed):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_auto_20200617_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='WorkflowFileParam',
            new_name='PsetFileParam',
        ),
        migrations.RenameModel(
            old_name='WorkflowParam',
            new_name='PsetParam',
        ),
        migrations.RenameModel(
            old_name='WorkflowPredefFileParam',
            new_name='PsetPredefFileParam',
        ),
        migrations.RunPython(add_one_pset, fakerevert),
        migrations.AddField(
            model_name='nextflowwfversion',
            name='paramset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analysis.ParameterSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psetfileparam',
            name='pset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analysis.ParameterSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psetparam',
            name='pset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analysis.ParameterSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psetpredeffileparam',
            name='pset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analysis.ParameterSet'),
            preserve_default=False,
        ),
    ]
