# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-06 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_remove_old_param_wf_coupling'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsetMultiFileParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_resultfiles', models.BooleanField(default=False)),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FileParam')),
                ('pset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.ParameterSet')),
            ],
        ),
    ]
