# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-07 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_psetmultifileparam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Param')),
            ],
        ),
    ]
