# Generated by Django 3.1.2 on 2020-10-21 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0012_quantfilechannelsample'),
        ('rawstatus', '0019_msinstrument_active'),
        ('analysis', '0025_auto_20201015_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSetname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisDatasetSetname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('setname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysissetname')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
                ('regex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisSampletable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samples', models.JSONField()),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.param')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisMzmldef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mzmldef', models.TextField()),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisIsoquant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('setname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysissetname')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisFractionRegex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisFileSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('sfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.storedfile')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisFileParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.fileparam')),
                ('sfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.storedfile')),
            ],
        ),
    ]
