# Generated by Django 3.1.2 on 2021-01-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0019_msinstrument_active'),
        ('analysis', '0027_auto_20201118_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisDSInputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='analysisdatasetsetname',
            constraint=models.UniqueConstraint(fields=('analysis', 'dataset'), name='uni_anadsets'),
        ),
        migrations.AddConstraint(
            model_name='analysisfileparam',
            constraint=models.UniqueConstraint(fields=('analysis', 'param', 'sfile'), name='uni_anafileparam'),
        ),
        migrations.AddConstraint(
            model_name='analysisfilesample',
            constraint=models.UniqueConstraint(fields=('analysis', 'sfile'), name='uni_anassamplefile'),
        ),
        migrations.AddConstraint(
            model_name='analysisisoquant',
            constraint=models.UniqueConstraint(fields=('analysis', 'setname'), name='uni_anaiso'),
        ),
        migrations.AddConstraint(
            model_name='analysissetname',
            constraint=models.UniqueConstraint(fields=('analysis', 'setname'), name='uni_anasets'),
        ),
        migrations.AddField(
            model_name='analysisdsinputfile',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis'),
        ),
        migrations.AddField(
            model_name='analysisdsinputfile',
            name='analysisdset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisdatasetsetname'),
        ),
        migrations.AddField(
            model_name='analysisdsinputfile',
            name='sfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.storedfile'),
        ),
        migrations.AddConstraint(
            model_name='analysisdsinputfile',
            constraint=models.UniqueConstraint(fields=('analysis', 'sfile'), name='uni_anainfile'),
        ),
    ]
