# Generated by Django 3.1.2 on 2021-08-20 11:52

from django.db import migrations


def fake_revert(a, s):
    pass


def decompose_missing_multifiles_to_db_from_job(apps, sch_ed):
    FileParam = apps.get_model('analysis', 'FileParam')
    Job = apps.get_model('jobs', 'Job')
    AnalysisFileParam = apps.get_model('analysis', 'AnalysisFileParam')
    tdbparam = FileParam.objects.get(nfparam='--tdb')
    for job in Job.objects.filter(funcname='run_nf_search_workflow', kwargs__inputs__multifiles__isnull=False):
        mfilecount_db = job.nextflowsearch.analysis.analysisfileparam_set.filter(param=tdbparam).count()
        try:
            mfilecount_job = len(job.kwargs['inputs']['multifiles']['--tdb'])
            if  mfilecount_db > 0 and mfilecount_job > mfilecount_db:
                job.nextflowsearch.analysis.analysisfileparam_set.filter(param=tdbparam).delete()
                for sfid in job.kwargs['inputs']['multifiles']['--tdb']:
                    AnalysisFileParam.objects.create(analysis=job.nextflowsearch.analysis, param=tdbparam, sfile_id=sfid)
        except KeyError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_nextflowsearch_token'),
    ]

    operations = [
        migrations.RunPython(decompose_missing_multifiles_to_db_from_job, fake_revert),
    ]
