# Generated by Django 3.2.7 on 2021-10-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_auto_20210910_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisbaseanalysis',
            name='rerun_from_psms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysisbaseanalysis',
            name='is_complement',
            field=models.BooleanField(default=False),
        ),
    ]
