# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-29 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180521_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='args',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='job',
            name='kwargs',
            field=models.CharField(max_length=100000),
        ),
    ]
