# Generated by Django 4.2 on 2024-10-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0019_deletes'),
        ('rawstatus', '0030_fileserver_fqdn'),
        ('analysis', '0052_outputfieldname_wfoutput_pipelineversionoutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cond_type', models.IntegerField(choices=[(0, 'Sample'), (1, 'Isobaric sample set'), (2, 'File'), (3, 'Sample group'), (4, 'Fraction'), (5, 'Isobaric channel')])),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upload_complete', models.BooleanField(default=False)),
                ('token', models.TextField()),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('wfoutput_found', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.wfoutput')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.species')),
            ],
        ),
        migrations.CreateModel(
            name='IdentifiedPeptide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField()),
                ('unimod_name', models.TextField(unique=True)),
                ('unimod_id', models.IntegerField(unique=True)),
                ('predefined_aa_list', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PeptideMolecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_pep', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeptideSeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProteinFasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('fafn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rawstatus.storedfile')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.protein')),
            ],
        ),
        migrations.CreateModel(
            name='PSM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdr', models.FloatField()),
                ('pep', models.FloatField()),
                ('scan', models.IntegerField()),
                ('score', models.FloatField()),
                ('charge', models.IntegerField()),
                ('mz', models.FloatField()),
                ('rt', models.FloatField()),
                ('filecond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.condition')),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.peptidemolecule')),
            ],
        ),
        migrations.CreateModel(
            name='QuantLabelMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mstulos.modification')),
                ('quanttype', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datasets.quanttype')),
            ],
        ),
        migrations.CreateModel(
            name='PSMMS1Quant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms1quant', models.FloatField()),
                ('psm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mstulos.psm')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.gene')),
                ('proteinfa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mstulos.proteinfasta')),
            ],
        ),
        migrations.CreateModel(
            name='PeptideProtein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinpos', models.IntegerField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.experiment')),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.peptideseq')),
                ('proteinfa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.proteinfasta')),
            ],
        ),
        migrations.CreateModel(
            name='PeptidePosteriorError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pep', models.FloatField()),
                ('idpep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mstulos.identifiedpeptide')),
            ],
        ),
        migrations.CreateModel(
            name='PeptideMS1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms1', models.FloatField()),
                ('idpep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mstulos.identifiedpeptide')),
            ],
        ),
        migrations.AddField(
            model_name='peptidemolecule',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.peptideseq'),
        ),
        migrations.CreateModel(
            name='PeptideIsoQuant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.condition')),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.peptidemolecule')),
            ],
        ),
        migrations.CreateModel(
            name='PeptideFDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdr', models.FloatField()),
                ('idpep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mstulos.identifiedpeptide')),
            ],
        ),
        migrations.CreateModel(
            name='MoleculeMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.modification')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.peptidemolecule')),
            ],
        ),
        migrations.AddField(
            model_name='identifiedpeptide',
            name='peptide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.peptidemolecule'),
        ),
        migrations.AddField(
            model_name='identifiedpeptide',
            name='setorsample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.condition'),
        ),
        migrations.CreateModel(
            name='GeneIsoQuant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.condition')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.gene')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.experiment'),
        ),
        migrations.AddField(
            model_name='condition',
            name='parent_conds',
            field=models.ManyToManyField(to='mstulos.condition'),
        ),
        migrations.CreateModel(
            name='AnalysisModSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residue', models.TextField()),
                ('fixed', models.BooleanField()),
                ('location', models.IntegerField(choices=[(0, 'Anywhere'), (1, 'N-term'), (2, 'C-term')])),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstulos.modification')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quantlabelmod',
            constraint=models.UniqueConstraint(fields=('quanttype', 'mod'), name='uni_qtype_mod'),
        ),
        migrations.AddConstraint(
            model_name='psm',
            constraint=models.UniqueConstraint(fields=('filecond', 'scan'), name='uni_psmscans'),
        ),
        migrations.AddConstraint(
            model_name='proteinfasta',
            constraint=models.UniqueConstraint(fields=('protein', 'fafn'), name='uni_prot_fa'),
        ),
        migrations.AddConstraint(
            model_name='peptideisoquant',
            constraint=models.UniqueConstraint(fields=('channel', 'peptide'), name='uni_isochpep'),
        ),
        migrations.AddConstraint(
            model_name='geneisoquant',
            constraint=models.UniqueConstraint(fields=('channel', 'gene'), name='uni_isochgene'),
        ),
        migrations.AddConstraint(
            model_name='gene',
            constraint=models.UniqueConstraint(fields=('name', 'organism'), name='uni_gene'),
        ),
    ]
