# Generated by Django 3.2.13 on 2023-01-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0043_remove_wfoutput_pepqval'),
        ('mstulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='name',
        ),
        migrations.AddField(
            model_name='experiment',
            name='analysis',
            field=models.OneToOneField(default=14394, on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExpAnalysis',
        ),
    ]
