# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-12 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0002_producer_shortname'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('filetype', models.CharField(max_length=20)),
            ],
        ),
    ]
