# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-30 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawstatus', '0005_auto_20180920_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('sfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.StoredFile')),
            ],
        ),
        migrations.CreateModel(
            name='UserFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=36, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('expires', models.DateTimeField()),
                ('finished', models.BooleanField(default=False)),
                ('filetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.StoredFileType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userfile',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.UserFileUpload'),
        ),
    ]
