# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-15 09:25
from __future__ import unicode_literals

from django.db import migrations, connection
from django.db.models import F



def initialize_regdate(apps, schema_editor):
    sql = 'UPDATE rawstatus_storedfile AS sf SET regdate=rf.date FROM rawstatus_rawfile AS rf WHERE sf.rawfile_id=rf.id'
    cursor = connection.cursor()
    cursor.execute(sql)


def fakerevert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0007_storedfile_regdate'),
    ]

    operations = [
        migrations.RunPython(initialize_regdate, fakerevert),
    ]
