# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0018_20200424_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='msinstrument',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
