# Generated by Django 3.1.2 on 2021-03-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0020_auto_20210319_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdcbackedupfile',
            name='is_dir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servershare',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
