# Generated by Django 3.2.13 on 2022-10-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0024_auto_20220923_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfiletype',
            name='is_rawdata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storedfiletype',
            name='stablefiles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='storedfiletype',
            name='user_uploadable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadtoken',
            name='archive_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadtoken',
            name='is_library',
            field=models.BooleanField(default=False),
        ),
    ]
