# Generated by Django 3.2.13 on 2022-11-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0026_alter_storedfiletype_stablefiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.uploadtoken'),
        ),
    ]
