# Generated by Django 3.2.13 on 2023-09-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0027_alter_userfile_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
