# Generated by Django 4.2 on 2024-05-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0028_alter_storedfile_checked'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storedfile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('servershare', 'path', 'filename', 'deleted'), name='uni_storedfile'),
        ),
    ]
