# Generated by Django 4.2 on 2024-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0029_storedfile_uni_storedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileserver',
            name='fqdn',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
