# Generated by Django 4.2 on 2024-10-07 20:57

from django.db import migrations, models

from rawstatus import models as rm

def islib_to_uptype(apps, s):
    UT = apps.get_model('rawstatus', 'UploadToken')
    UT.objects.filter(is_library=True).update(uploadtype=rm.UploadToken.UploadFileType.LIBRARY)
    UT.objects.filter(is_library=False).update(uploadtype=rm.UploadToken.UploadFileType.USERFILE)


def uptype_to_islib(apps, s):
    UT = apps.get_model('rawstatus', 'UploadToken')
    UT.objects.filter(uploadtype=UT.UploadFileType.LIBRARY).update(is_library=True)
    UT.objects.filter(uploadtype=UT.UploadFileType.USERFILE).update(is_library=False)


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0030_fileserver_fqdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtoken',
            name='uploadtype',
            field=models.IntegerField(choices=[(1, 'Raw file'), (2, 'Analysis result'), (3, 'Shared file for all users'), (4, 'User upload')], default=1),
            preserve_default=False,
        ),
        migrations.RunPython(islib_to_uptype, uptype_to_islib),
        migrations.RemoveField(
            model_name='uploadtoken',
            name='is_library',
        ),
    ]
