name: integration-tests
run-name: Run integration tests
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker buildx bake --file src/docker/docker-compose-testing.yml --file src/docker/docker-compose-gha-cache.json
            - run: bash run_lint.sh

    integration-tests:
        runs-on: ubuntu-latest
        needs: linting
        steps:
            - uses: actions/checkout@v4
            - run: bash .github/run_tests_integration.sh

    unit-tests:
        runs-on: ubuntu-latest
        needs: linting
        steps:
            - uses: actions/checkout@v4
            - run: bash .github/run_tests_unit.sh
